# Generated by Django 5.1.6 on 2025-03-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacytest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='meta_data',
            field=models.JSONField(null=True),
        ),
    ]
