# Generated by Django 5.1.6 on 2025-04-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacytest', '0003_supplier_medicine_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacytest.supplier'),
        ),
    ]
